import type { ApplicationDetailInfo, ApplicationRow, ApplicationStatus, JobListing, PlacementFeedbackInsight, ProfileChecklistItem, StudentProfileSnapshot, WorkflowStepStatus } from "./types";
import { AlertTriangle, BriefcaseBusiness, CheckCircle2, CircleMinus, Clock3, Trophy } from "lucide-react";

export const jobListings: JobListing[] = [
  {
    id: "tcs",
    company: "TCS",
    companyName: "Tata Consultancy Services",
    logo: "tcs",
    role: "Software Engineer",
    skills: ["C, C++, Java", "SQL", "OOPs", "+2"],
    location: "Bangalore",
    ctc: "₹7.5 LPA",
    applyBy: "05 Sep 2026",
    daysLeft: 5,
    match: 92,
    matchLabel: "Excellent",
  },
  {
    id: "infosys",
    company: "Infosys",
    companyName: "Infosys",
    logo: "Infosys",
    role: "System Engineer",
    skills: ["Python", "SQL", "Linux", "+1"],
    location: "Pune",
    ctc: "₹6.5 LPA",
    applyBy: "08 Sep 2026",
    daysLeft: 8,
    match: 87,
    matchLabel: "Great",
  },
  {
    id: "zoho",
    company: "Zoho",
    companyName: "Zoho Corporation",
    logo: "ZOHO",
    role: "Software Developer",
    skills: ["JavaScript", "React", "Node.js", "+1"],
    location: "Chennai",
    ctc: "₹8.0 LPA",
    applyBy: "12 Sep 2026",
    daysLeft: 12,
    match: 82,
    matchLabel: "Good",
  },
  {
    id: "wipro",
    company: "Wipro",
    companyName: "Wipro",
    logo: "wipro",
    role: "Project Engineer",
    skills: ["Java", "SQL", "DSA", "+1"],
    location: "Hyderabad",
    ctc: "₹6.0 LPA",
    applyBy: "18 Sep 2026",
    daysLeft: 18,
    match: 78,
    matchLabel: "Good",
  },
  {
    id: "accenture",
    company: "Accenture",
    companyName: "Accenture",
    logo: "accenture",
    role: "Associate Software Engineer",
    skills: ["Python", "SQL", "OOPs", "+2"],
    location: "Bangalore",
    ctc: "₹7.0 LPA",
    applyBy: "20 Sep 2026",
    daysLeft: 20,
    match: 74,
    matchLabel: "Good",
  },
  {
    id: "cognizant",
    company: "Cognizant",
    companyName: "Cognizant",
    logo: "cognizant",
    role: "Graduate Engineer Trainee",
    skills: ["C#", ".NET", "SQL", "+1"],
    location: "Kolkata",
    ctc: "₹6.5 LPA",
    applyBy: "22 Sep 2026",
    daysLeft: 22,
    match: 72,
    matchLabel: "Fair",
  },
  {
    id: "lti-mindtree",
    company: "LTI Mindtree",
    companyName: "LTI Mindtree",
    logo: "LTI",
    role: "Software Engineer",
    skills: ["Java", "Spring", "SQL", "+1"],
    location: "Mumbai",
    ctc: "₹6.8 LPA",
    applyBy: "25 Sep 2026",
    daysLeft: 25,
    match: 69,
    matchLabel: "Fair",
  },
  {
    id: "capgemini",
    company: "Capgemini",
    companyName: "Capgemini",
    logo: "Capgemini",
    role: "Analyst",
    skills: ["Python", "SQL", "Excel", "+1"],
    location: "Bangalore",
    ctc: "₹5.5 LPA",
    applyBy: "28 Sep 2026",
    daysLeft: 28,
    match: 65,
    matchLabel: "Fair",
  },
];

export const jobFilterOptions = {
  company: ["All Companies", "TCS", "Infosys", "Zoho", "Wipro", "Accenture"],
  role: [
    "All Roles",
    "Software Engineer",
    "System Engineer",
    "Developer",
    "Analyst",
  ],
  location: [
    "All Locations",
    "Bangalore",
    "Pune",
    "Chennai",
    "Hyderabad",
    "Mumbai",
  ],
  type: ["All Job Types", "Full-time", "Internship", "Contract"],
};

export const studentProfileSnapshot: StudentProfileSnapshot = {
  branch: "CSE",
  cgpa: "8.72",
  skills: ["Java", "SQL", "OOPs", "DSA", "Python", "React"],
  projectCount: 3,
};

export const studentProfileData = {
  name: "Arjun Mehta",
  initials: "AM",
  registrationNumber: "CSE2026-014",
  department: "Computer Science & Engineering",
  program: "B.E. Computer Science",
  batch: "2026",
  semester: "7th Semester",
  email: "arjun.mehta@lumina.edu",
  phone: "+91 98765 43210",
  location: "Bengaluru, Karnataka",
  dateOfBirth: "14 May 2004",
  gender: "Male",
  cgpa: "8.72",
  percentage: "82.4%",
  attendance: "91%",
  backlogs: "0",
  profileCompletion: 100,
  semesterScores: [
    { label: "Sem 1", score: "8.1", percentage: 81, attendance: 88, backlogs: 0, file: "sem1_marksheet.pdf" },
    { label: "Sem 2", score: "8.4", percentage: 84, attendance: 90, backlogs: 0, file: "sem2_marksheet.pdf" },
    { label: "Sem 3", score: "8.6", percentage: 86, attendance: 89, backlogs: 0, file: "sem3_marksheet.pdf" },
    { label: "Sem 4", score: "8.8", percentage: 88, attendance: 92, backlogs: 0, file: "sem4_marksheet.pdf" },
    { label: "Sem 5", score: "8.9", percentage: 89, attendance: 93, backlogs: 0, file: "sem5_marksheet.pdf" },
    { label: "Sem 6", score: "9.1", percentage: 91, attendance: 94, backlogs: 0, file: "sem6_marksheet.pdf" },
    { label: "Sem 7", score: "Pending", percentage: 0, attendance: 0, backlogs: 0, file: "" },
  ],
  skillGroups: [
    { label: "Programming", skills: ["Java", "Python", "C++", "JavaScript"] },
    { label: "Core CS", skills: ["DSA", "OOPs", "DBMS", "Computer Networks"] },
    { label: "Tools & Frameworks", skills: ["React", "Node.js", "Git", "SQL"] },
  ],
  skillsList: ["Java", "Python", "C++", "JavaScript", "DSA", "DBMS", "Computer Networks", "React", "Node.js", "Git", "SQL"],
  projects: [
    { id: "1", title: "Placement Prep AI", type: "Full-stack web application", dates: "Jan 2025 – Apr 2025", description: "Personalized placement preparation dashboard with job matching and interview insights.", technologies: ["React", "Node.js", "MongoDB"], githubUrl: "https://github.com/arjun/placement-prep-ai", reportFile: "" },
    { id: "2", title: "Smart Attendance System", type: "Academic project", dates: "Aug 2024 – Dec 2024", description: "Automated attendance tracking system with reports for students and faculty.", technologies: ["Python", "Flask", "MySQL"], githubUrl: "https://github.com/arjun/smart-attendance", reportFile: "" },
    { id: "3", title: "Campus Connect Portal", type: "Team project", dates: "Jan 2024 – May 2024", description: "Student community platform for events, announcements, and peer collaboration.", technologies: ["JavaScript", "Express", "PostgreSQL"], githubUrl: "https://github.com/arjun/campus-connect", reportFile: "" },
  ],
  internships: [
    { id: "1", role: "Frontend Developer Intern", company: "BlueOrbit Technologies", duration: "May 2025 – Jul 2025", description: "Built responsive dashboard screens and reusable React components.", certificateFile: "BlueOrbit_Certificate.pdf", certificateSize: "1.2 MB" },
    { id: "2", role: "Software Engineering Intern", company: "Lumina Labs", duration: "Jan 2025 – Mar 2025", description: "Worked on REST APIs, database queries, and automated testing.", certificateFile: "LuminaLabs_Intern_Certificate.pdf", certificateSize: "1.1 MB" },
  ],
  resume: { name: "Arjun_Mehta_Resume_2026.pdf", size: "1.2 MB", updated: "28 Aug 2026" },
  sports: [
    { id: "1", title: "University Cricket Team", detail: "Vice Captain · Inter-college runner-up", period: "2024 – 2026", certificateFile: "cricket_certificate.jpg" },
    { id: "2", title: "100m Athletics", detail: "Department sports meet · Gold medal", period: "2025", certificateFile: "athletics_certificate.pdf" },
  ],
  extracurriculars: [
    { id: "1", title: "Coding Club Lead", detail: "Organised weekly problem-solving sessions for 60+ students.", period: "2024 – Present", certificateFile: "coding_club_certificate.pdf" },
    { id: "2", title: "Placement Cell Volunteer", detail: "Supported employer events and student interview coordination.", period: "2025", certificateFile: "" },
  ],
  awards: [
    { id: "1", title: "Hackathon Winner", detail: "1st place · Lumina Buildathon 2025", year: "2025", certificateFile: "hackathon_certificate.pdf" },
    { id: "2", title: "Academic Excellence Award", detail: "Top 10% of the department", year: "2024", certificateFile: "academic_award.pdf" },
  ],
};

export const placementReadinessChecklist: ProfileChecklistItem[] = [
  { label: "CGPA", status: "done" },
  { label: "Certificates", status: "done" },
  { label: "Resume", status: "done" },
  { label: "Add 1 more project", status: "warning" },
  { label: "Projects", status: "done" },
  { label: "Add internship details", status: "warning" },
  { label: "Skills", status: "done" },
];

export const placementFeedbackByCompany: Record<string, PlacementFeedbackInsight> = {
  TCS: {
    reviewedStudents: 320,
    averageRating: 4.2,
    focusStage: "Technical interview",
    commonChallenge: "DSA under time pressure",
    toughRoundShare: 38,
    copingStrategies: ["Clarify the approach before coding.", "Think aloud while comparing solutions.", "Test edge cases before optimising."],
    improvementSkills: ["Timed DSA practice", "Complexity analysis", "Project explanation"],
    successfulPattern: "Students who practised timed problems and explained their approach clearly progressed more often.",
    nextAction: "Complete two timed DSA problems and rehearse one project walkthrough before the technical round.",
  },
  Infosys: {
    reviewedStudents: 246,
    averageRating: 4.1,
    focusStage: "Online assessment",
    commonChallenge: "Aptitude speed and accuracy",
    toughRoundShare: 34,
    copingStrategies: ["Use a fixed time limit per question.", "Skip and return instead of getting stuck.", "Review SQL and Python patterns daily."],
    improvementSkills: ["Aptitude speed", "SQL joins", "Python fundamentals"],
    successfulPattern: "Recent candidates found a short daily aptitude routine more useful than last-minute preparation.",
    nextAction: "Set aside 30 minutes for aptitude practice, then revise Python and SQL fundamentals.",
  },
  Zoho: {
    reviewedStudents: 184,
    averageRating: 4.4,
    focusStage: "Problem-solving round",
    commonChallenge: "Turning ideas into working code",
    toughRoundShare: 46,
    copingStrategies: ["Start with a simple working solution.", "Explain trade-offs as you improve it.", "Practise coding without autocomplete."],
    improvementSkills: ["Problem decomposition", "JavaScript fundamentals", "Debugging"],
    successfulPattern: "Candidates who built and discussed one complete project stood out in the later rounds.",
    nextAction: "Prepare a concise demo of your strongest project and practise coding it from a blank file.",
  },
};

export const defaultPlacementFeedback: PlacementFeedbackInsight = {
  reviewedStudents: 120,
  averageRating: 4.0,
  focusStage: "Technical interview",
  commonChallenge: "Explaining the reasoning behind solutions",
  toughRoundShare: 31,
  copingStrategies: ["Restate the problem in your own words.", "Talk through trade-offs before committing.", "Finish with a quick test and recap."],
  improvementSkills: ["Problem solving", "Technical communication", "Core role skills"],
  successfulPattern: "Candidates who connected their projects to the role and explained trade-offs made stronger impressions.",
  nextAction: "Review the core requirements and prepare one project story that demonstrates them.",
};

export const applicationRows: ApplicationRow[] = [
  {
    id: "tcs",
    company: "TCS",
    companyName: "Tata Consultancy Services",
    logo: "tcs",
    role: "Software Engineer",
    location: "Bangalore",
    ctc: "₹7.5 LPA",
    appliedOn: "05 Sep 2026",
    status: "Shortlisted",
    updated: "Updated on 10 Sep 2026",
    nextStep: "Technical Interview",
    nextDate: "On 18 Sep 2026",
  },
  {
    id: "infosys",
    company: "Infosys",
    companyName: "Infosys",
    logo: "Infosys",
    role: "System Engineer",
    location: "Pune",
    ctc: "₹6.5 LPA",
    appliedOn: "08 Sep 2026",
    status: "In Process",
    updated: "Updated on 12 Sep 2026",
    nextStep: "HR Interview",
    nextDate: "On 20 Sep 2026",
  },
  {
    id: "zoho",
    company: "Zoho",
    companyName: "Zoho Corporation",
    logo: "ZOHO",
    role: "Software Developer",
    location: "Chennai",
    ctc: "₹8.0 LPA",
    appliedOn: "12 Sep 2026",
    status: "In Process",
    updated: "Updated on 14 Sep 2026",
    nextStep: "Group Discussion",
    nextDate: "On 16 Sep 2026",
  },
  {
    id: "wipro",
    company: "Wipro",
    companyName: "Wipro",
    logo: "wipro",
    role: "Project Engineer",
    location: "Hyderabad",
    ctc: "₹6.0 LPA",
    appliedOn: "18 Sep 2026",
    status: "Rejected",
    updated: "Updated on 21 Sep 2026",
    nextStep: "Not Selected",
    nextDate: "Thank you for applying.",
  },
  {
    id: "accenture",
    company: "Accenture",
    companyName: "Accenture",
    logo: "accenture",
    role: "Associate Software Engineer",
    location: "Bangalore",
    ctc: "₹7.0 LPA",
    appliedOn: "20 Sep 2026",
    status: "Offer",
    updated: "Updated on 22 Sep 2026",
    nextStep: "Offer Received",
    nextDate: "On 22 Sep 2026",
  },
  {
    id: "cognizant",
    company: "Cognizant",
    companyName: "Cognizant",
    logo: "cognizant",
    role: "Graduate Engineer Trainee",
    location: "Kolkata",
    ctc: "₹6.5 LPA",
    appliedOn: "22 Sep 2026",
    status: "Withdrawn",
    updated: "Updated on 23 Sep 2026",
    nextStep: "Application Withdrawn",
    nextDate: "By you on 23 Sep 2026",
  },
];

export const applicationTabs: {
  label: string;
  status?: ApplicationStatus;
  count: number;
}[] = [
  { label: "All", count: 12 },
  { label: "Shortlisted", status: "Shortlisted", count: 4 },
  { label: "In Process", status: "In Process", count: 3 },
  { label: "Offer", status: "Offer", count: 1 },
  { label: "Rejected", status: "Rejected", count: 3 },
  { label: "Withdrawn", status: "Withdrawn", count: 1 },
];

export const applicationDetails: Record<string, ApplicationDetailInfo> = {
  tcs: {
    jobDescription:
      "TCS is hiring Software Engineers for its Bangalore delivery center to work on enterprise application development and modernization projects for global clients, as part of the Ninja / Digital hiring track.",
    responsibilities: [
      "Design, develop and unit-test application modules",
      "Participate in code reviews and daily stand-ups",
      "Debug and resolve production support issues",
    ],
    eligibility: [
      "B.E. / B.Tech, CGPA 6.5+, no active backlogs",
      "Core Java, SQL and OOP fundamentals",
      "Good communication and problem-solving skills",
    ],
    workflow: [
      { label: "Applied", date: "05 Sep", status: "done" },
      { label: "Shortlisted", date: "10 Sep", status: "done" },
      { label: "Technical Interview", date: "18 Sep", status: "current" },
      { label: "HR Interview", date: "Pending", status: "pending" },
      { label: "Offer", date: "Pending", status: "pending" },
    ],
    documents: [{ name: "Job_Description_TCS_SE.pdf", size: "180 KB" }],
  },
  infosys: {
    jobDescription:
      "Infosys is hiring System Engineers for application development, testing and support projects across global client accounts as part of the campus hiring track.",
    responsibilities: [
      "Support design, coding and testing of software modules",
      "Assist in requirement analysis and documentation",
      "Coordinate with senior engineers on delivery timelines",
    ],
    eligibility: [
      "B.E. / B.Tech, CGPA 6.0+, no active backlogs",
      "Python, SQL and Linux fundamentals",
      "Strong analytical and communication skills",
    ],
    workflow: [
      { label: "Applied", date: "08 Sep", status: "done" },
      { label: "Shortlisted", date: "12 Sep", status: "done" },
      { label: "Technical Interview", date: "15 Sep", status: "done" },
      { label: "HR Interview", date: "20 Sep", status: "current" },
      { label: "Offer", date: "Pending", status: "pending" },
    ],
    documents: [{ name: "Job_Description_Infosys_SE.pdf", size: "165 KB" }],
  },
  zoho: {
    jobDescription:
      "Zoho Corporation is hiring Software Developers to build and maintain features across its suite of SaaS products used by businesses worldwide.",
    responsibilities: [
      "Build and maintain product features end-to-end",
      "Write clean, tested and maintainable code",
      "Collaborate closely with product and QA teams",
    ],
    eligibility: [
      "B.E. / B.Tech, CGPA 7.0+, no active backlogs",
      "JavaScript, React and Node.js fundamentals",
      "Strong problem-solving ability",
    ],
    workflow: [
      { label: "Applied", date: "12 Sep", status: "done" },
      { label: "Shortlisted", date: "14 Sep", status: "done" },
      { label: "Group Discussion", date: "16 Sep", status: "current" },
      { label: "Technical Interview", date: "Pending", status: "pending" },
      { label: "Offer", date: "Pending", status: "pending" },
    ],
    documents: [{ name: "Job_Description_Zoho_Developer.pdf", size: "150 KB" }],
  },
  wipro: {
    jobDescription:
      "Wipro is hiring Project Engineers to support delivery of client projects across infrastructure and application services.",
    responsibilities: [
      "Assist project leads with planning and execution",
      "Prepare status reports and documentation",
      "Support testing and deployment activities",
    ],
    eligibility: [
      "B.E. / B.Tech, CGPA 6.0+, no active backlogs",
      "Java, SQL and DSA fundamentals",
      "Good communication skills",
    ],
    workflow: [
      { label: "Applied", date: "18 Sep", status: "done" },
      { label: "Shortlisted", date: "19 Sep", status: "done" },
      { label: "Technical Interview", date: "21 Sep", status: "done" },
      { label: "HR Interview", date: "Not Selected", status: "rejected" },
      { label: "Offer", date: "—", status: "pending" },
    ],
    documents: [{ name: "Job_Description_Wipro_PE.pdf", size: "140 KB" }],
  },
  accenture: {
    jobDescription:
      "Accenture is hiring Associate Software Engineers to work on application development and modernization engagements for global clients.",
    responsibilities: [
      "Develop and test application components",
      "Participate in agile ceremonies and sprint planning",
      "Document technical designs and decisions",
    ],
    eligibility: [
      "B.E. / B.Tech, CGPA 6.5+, no active backlogs",
      "Python, SQL and OOP fundamentals",
      "Adaptability and teamwork",
    ],
    workflow: [
      { label: "Applied", date: "20 Sep", status: "done" },
      { label: "Shortlisted", date: "20 Sep", status: "done" },
      { label: "Technical Interview", date: "21 Sep", status: "done" },
      { label: "HR Interview", date: "22 Sep", status: "done" },
      { label: "Offer", date: "22 Sep", status: "done" },
    ],
    documents: [{ name: "Job_Description_Accenture_ASE.pdf", size: "155 KB" }],
  },
  cognizant: {
    jobDescription:
      "Cognizant is hiring Graduate Engineer Trainees for its technology services and consulting teams working with global clients.",
    responsibilities: [
      "Support development and testing of client applications",
      "Learn and apply engineering best practices",
      "Participate in structured training programs",
    ],
    eligibility: [
      "B.E. / B.Tech, CGPA 6.0+, no active backlogs",
      "C#, .NET and SQL fundamentals",
      "Willingness to learn and relocate",
    ],
    workflow: [
      { label: "Applied", date: "22 Sep", status: "done" },
      { label: "Shortlisted", date: "Withdrawn", status: "withdrawn" },
      { label: "Technical Interview", date: "Pending", status: "pending" },
      { label: "HR Interview", date: "Pending", status: "pending" },
      { label: "Offer", date: "Pending", status: "pending" },
    ],
    documents: [{ name: "Job_Description_Cognizant_GET.pdf", size: "145 KB" }],
  },
};

export const workflowStepStyles: Record<
  WorkflowStepStatus,
  { ring: string; icon: string; label: string }
> = {
  done: {
    ring: "border-emerald-500 text-emerald-600",
    icon: "text-emerald-600",
    label: "text-slate-800",
  },
  current: {
    ring: "border-cyan-500 text-cyan-600",
    icon: "text-cyan-600",
    label: "text-slate-800",
  },
  pending: {
    ring: "border-slate-200 text-slate-300",
    icon: "text-slate-300",
    label: "text-slate-400",
  },
  rejected: {
    ring: "border-rose-500 text-rose-500",
    icon: "text-rose-500",
    label: "text-slate-800",
  },
  withdrawn: {
    ring: "border-slate-300 text-slate-400",
    icon: "text-slate-400",
    label: "text-slate-400",
  },
};

export const applicationSummary = [
  {
    label: "Total Applications",
    value: "12",
    icon: BriefcaseBusiness,
    tone: "bg-violet-50 text-violet-600",
  },
  {
    label: "Shortlisted",
    value: "4",
    icon: CheckCircle2,
    tone: "bg-emerald-50 text-emerald-600",
  },
  {
    label: "In Process",
    value: "3",
    icon: Clock3,
    tone: "bg-blue-50 text-blue-600",
  },
  {
    label: "Rejected",
    value: "3",
    icon: AlertTriangle,
    tone: "bg-rose-50 text-rose-600",
  },
  {
    label: "Offer Received",
    value: "1",
    icon: Trophy,
    tone: "bg-violet-50 text-violet-600",
  },
  {
    label: "Withdrawn",
    value: "1",
    icon: CircleMinus,
    tone: "bg-slate-100 text-slate-600",
  },
];
